package biblio;

public class BiblioString {
    
    private BiblioString(){}

    public static String nomVAE = "VAE";
    public static String sauvegardeString = "Sauvegarder";
    public static String autreString = "Autre";
    public static String administrateurString = "Administrateur";
    public static String pseudoErreur = " - Pseudo ou mot de passe incorrecte.";
    public static String cheminflecheHaut = "./images/flecheHaut.png";
    public static String cheminflecheBas = "./images/flecheBas.png";
    public static String nbCaracRestant = "Nombre de caractères restant : ";
    public static String genererExempleText = "Bonjour\n\n\nJe me permet de vous envoyer ce mail car ...\n\n\nCordialement";
    public static String cheminOeilFermer = "./images/oeilFerme.png";
    public static String cheminOeilOuvert = "./images/oeilOuvert.png";
    public static String connexionString = "Connexion";
    public static String SeConnecterString = "Se connecter";
    public static String inscriptionString = "Inscription";
    public static String SInscrireString = "S'inscrire";
    public static String utilisateurString = "Utilisateur";
    public static String deconnexionString = "Déconnexion";
    public static String resetString = "Reset";
    public static String exempleString = "Exemple";
    public static String quitterString = "Quitter";
    public static String profilString = "Profil";
    public static String couleurString = "006b7b";
    public static String couleurNoirString = "0x00000000";
    public static String couuleurString3 = "0x014751ff";
    public static String couleurBlancString = "0xffffffff";
    public static String couleurString2 = "014751";
    public static String imageRechercherString = "./images/rechercher.png";
    public static String questionDejaClient = "Déjà client ?";
    public static String imageMarteauString = "./images/marteau.png";
    public static String policeArial = "Arial";
    public static String imageFuseeString = "./images/fusee.png";
    public static String perleRareString = "1 - Trouver la perle rare";
    public static String pseudoString = "Pseudo";
    public static String videString = "";
    public static String motDePasseString = "Mot de passe";
    public static String enrichirBienString = "2 - Enchérissez sur le bien";
    public static String profiterString = "3 - Payez et profitez !";
    public static String questionNouveauClient = "Nouveau client ?";
    public static String voitureString = "Voiture";
    public static String electroniqueString = "Électronique";
    public static String testString = "Test";
    public static String encherirString = "Enchérir";
    public static String tempsRestantString = "Temps restant : ";
    public static String euroString = "€";
    public static String prixActuellString = "Prix actuelle : ";
    public static String creeUneEnchereString = "Crée une enchère";
    public static String cheminImageAppareilPhoto = "images/apareilPhot.jpg";
    public static String ajouterImageString = "Ajouter image";
    public static String supprimerImageString = "Supprimer image";
    public static String imageString = "images";
    public static String fichierSelectionnerString = "Fichier sélectionné : ";
    public static String titreLabelString = "Titre";
    public static String dateDeDebutLabelString = "Date de début";
    public static String dateDeFinLabelString ="Date de fin";
    public static String categorieLabelString = "Catégorie";
    public static String votreObjetLabelString = "Votre Objet";
    public static String ddescriptionLabelString = "Description";
    public static String prixMinLabelString = "Prix min";
    public static String prixDeBaseLabelString = "Prix de base";
    public static String emailString = "Email";
    public static String arobaseString = "@";
    public static String spaceString = " ";
    public static String pointComString = ".com";
    public static String pointFrString = ".fr";
    public static String dejaClientString = "Déjà client ?";
    public static String userLoginString = "userLogin:";
    public static String nomBDString = "bdName:";
    public static String nomServString = "serverName:";
    public static String cheminBDString = "./LoginBDD.yml";
    public static String vaeString = "Vente aux enchères";
    public static String bordureRougeString = "-fx-border-color: red;";
    public static String nouveauClientString = "Nouveau client ?";
    public static String mesEncheresString = "Mes enchères";
    public static String creeEnCliquantString = "Vous pouvez en créer une en cliquant sur ";
    public static String plusDenchereString = "Il n'y a plus d'enchères en cours.";
    public static String tempsString = "00:00:00";
    public static String userMDPString = "userPassword:";
    public static String deuxPointString = ":";
    public static String erreurDriverString = "Driver MySQL non trouvé !";
    public static String connexionImposibleString = "Impossibilité à l'application de se connecter à la base de donnée !";
    public static String popupQuitterString = "Voulez-vous vraiment quitter l'application ?";
    public static String popupdecoString = "Voulez-vous vraiment vous déconnecter ?";


}
